openapi: 3.1.0
info:
  title: API to retrieve Takeblip Github C# repositories data
  description: |
    This API retrieves all the Github repositories from company TakeBlip and filters them to return the 5 oldest C# repositories by ascending order.
  version: 1.0
paths:
  /:
    get:
      description: Retrieves a json array containing the full name, description and the url of the avatar of Takeblip's Github user of each one of its 5 oldest C# repositories.
      responses:
        "200":
          description: "Success"
          content:
            application/json:
              schema:
                type: object
                properties:
                    full_name:
                      type: string
                    description:
                      type: string
                    avatar_url:
                      type: string
        "400":
          description: "Error"

    # https://oai.github.io/Documentation/specification-content.html